# Generated by Django 5.1.4 on 2024-12-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Division',
            new_name='division',
        ),
    ]
